//
//  bmailTests.swift
//  bmailTests
//
//  Created by Christopher Wong on 5/23/26.
//

import CryptoKit
import Foundation
import Testing
@testable import bmail

// MARK: - Test vectors (generated by scripts/gen-ios-interop-vectors.mjs)
//
// Fixed CEK: 32 bytes of 0x42
// Nonces are deterministic (fixed per vector) so frames are reproducible.
// Run the gen script again to regenerate if the wire format changes.

private let kCEK = Data(repeating: 0x42, count: 32)

// Vector 0: "hello world", chunkIndex=0, isFinal=true, nonce=0x01*24
private let kVec0FramedB64 = "gAAACwEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ+NSNoPIE3/UEOUGw46htGN3EgVzjIZDESNYA=="
private let kVec0Plaintext = Data("hello world".utf8)

// Vector 2: empty plaintext, chunkIndex=42, isFinal=true, nonce=0x03*24
private let kVec2FramedB64 = "gAAAAAMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA8LHTr5eTjuYs/BN2LnyfmE="

// Argon2id vector:
//   password="passphrase", salt=0x01*16, m=65536, t=3, p=4, hashLen=32
private let kArgon2ExpectedB64 = "TWVulYaDnW1aKbkagJ65H3YPHjyqJ3r7ZcqNm8pla3k="

// HKDF-SHA256 vector:
//   ikm=0x03*32, salt=0x04*16, info="cfemail-test", L=32
private let kHkdfExpectedB64 = "CovUOUeIXeKi7DY7g3ofvwUkoWx2bWAVYa417dmtIas="

// MARK: - ChunkedAEAD — web↔iOS interop tests

@Suite("ChunkedAEAD — web↔iOS interop")
struct ChunkedAEADInteropTests {

    // -----------------------------------------------------------------------
    // Decrypt web-generated vectors with iOS implementation
    // -----------------------------------------------------------------------

    @Test("Decrypt web vector 0: 'hello world', index=0, isFinal=true")
    func decryptWebVector0() throws {
        let framed = Data(base64Encoded: kVec0FramedB64)!
        let (plaintext, isFinal) = try ChunkedAEAD.decryptChunk(
            cek: kCEK,
            framedChunk: framed,
            chunkIndex: 0
        )
        #expect(plaintext == kVec0Plaintext)
        #expect(isFinal == true)
    }

    @Test("Decrypt web vector 1: 100 KiB of 0xAB, index=0, isFinal=false")
    func decryptWebVector1() throws {
        // Load from the JSON resource file to avoid a 137 KB base64 literal.
        let bundle = Bundle(for: BmailTestsHelper.self)
        guard let url = bundle.url(forResource: "InteropVectors", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let json = try? JSONDecoder().decode(InteropVectors.self, from: data)
        else {
            Issue.record("InteropVectors.json not found in test bundle")
            return
        }
        let v = json.chunkedAEAD[1]
        let framed = Data(base64Encoded: v.framedChunk_b64)!
        let expectedPlaintext = Data(repeating: 0xab, count: 100 * 1024)

        let (plaintext, isFinal) = try ChunkedAEAD.decryptChunk(
            cek: kCEK,
            framedChunk: framed,
            chunkIndex: 0
        )
        #expect(plaintext == expectedPlaintext)
        #expect(isFinal == false)
    }

    @Test("Decrypt web vector 2: empty plaintext, index=42, isFinal=true")
    func decryptWebVector2() throws {
        let framed = Data(base64Encoded: kVec2FramedB64)!
        let (plaintext, isFinal) = try ChunkedAEAD.decryptChunk(
            cek: kCEK,
            framedChunk: framed,
            chunkIndex: 42
        )
        #expect(plaintext == Data())
        #expect(isFinal == true)
    }

    // -----------------------------------------------------------------------
    // Pure-Swift round-trips
    // -----------------------------------------------------------------------

    @Test("Round-trip: arbitrary plaintext, non-final chunk")
    func roundTripNonFinal() throws {
        let message = Data("The quick brown fox jumps over the lazy dog.".utf8)
        let framed = try ChunkedAEAD.encryptChunk(cek: kCEK, plaintext: message, chunkIndex: 7, isFinal: false)
        let (pt, isFinal) = try ChunkedAEAD.decryptChunk(cek: kCEK, framedChunk: framed, chunkIndex: 7)
        #expect(pt == message)
        #expect(isFinal == false)
    }

    @Test("Round-trip: empty plaintext")
    func roundTripEmpty() throws {
        let framed = try ChunkedAEAD.encryptChunk(cek: kCEK, plaintext: Data(), chunkIndex: 0, isFinal: true)
        let (pt, isFinal) = try ChunkedAEAD.decryptChunk(cek: kCEK, framedChunk: framed, chunkIndex: 0)
        #expect(pt == Data())
        #expect(isFinal == true)
    }

    @Test("Round-trip: large plaintext (1 MiB)")
    func roundTripLarge() throws {
        let message = Data(repeating: 0xde, count: 1 * 1024 * 1024)
        let framed = try ChunkedAEAD.encryptChunk(cek: kCEK, plaintext: message, chunkIndex: 0, isFinal: true)
        let (pt, isFinal) = try ChunkedAEAD.decryptChunk(cek: kCEK, framedChunk: framed, chunkIndex: 0)
        #expect(pt == message)
        #expect(isFinal == true)
    }

    @Test("Round-trip: isFinal flag is preserved")
    func roundTripFinalFlag() throws {
        for (idx, expected) in [(0, false), (1, false), (2, true)] {
            let msg = Data(repeating: UInt8(idx), count: 16)
            let framed = try ChunkedAEAD.encryptChunk(
                cek: kCEK, plaintext: msg,
                chunkIndex: UInt32(idx), isFinal: expected
            )
            let (_, isFinal) = try ChunkedAEAD.decryptChunk(
                cek: kCEK, framedChunk: framed, chunkIndex: UInt32(idx)
            )
            #expect(isFinal == expected)
        }
    }

    // -----------------------------------------------------------------------
    // Negative tests
    // -----------------------------------------------------------------------

    @Test("Wrong chunkIndex causes AEAD tag failure")
    func wrongChunkIndex() throws {
        let framed = try ChunkedAEAD.encryptChunk(cek: kCEK, plaintext: kVec0Plaintext, chunkIndex: 3, isFinal: false)
        // Decrypting with chunkIndex=4 must fail — AAD mismatch breaks the tag.
        #expect(throws: (any Error).self) {
            try ChunkedAEAD.decryptChunk(cek: kCEK, framedChunk: framed, chunkIndex: 4)
        }
    }

    @Test("Wrong isFinal in decryption context causes AEAD tag failure")
    func wrongIsFinalViaManipulatedHeader() throws {
        let message = Data("sensitive".utf8)
        var framed = try ChunkedAEAD.encryptChunk(cek: kCEK, plaintext: message, chunkIndex: 0, isFinal: false)
        // Flip the high bit of byte 0 to forge isFinal=true in the header.
        // The AEAD tag was computed with isFinal=false, so decryption must fail.
        framed[framed.startIndex] ^= 0x80
        #expect(throws: (any Error).self) {
            try ChunkedAEAD.decryptChunk(cek: kCEK, framedChunk: framed, chunkIndex: 0)
        }
    }

    @Test("Truncated header (< 44 bytes) is rejected")
    func truncatedHeader() {
        let truncated = Data(repeating: 0x00, count: 43)
        #expect(throws: (any Error).self) {
            try ChunkedAEAD.decryptChunk(cek: kCEK, framedChunk: truncated, chunkIndex: 0)
        }
    }

    @Test("Truncated frame (header declares more bytes than present) is rejected")
    func truncatedFrame() throws {
        var framed = try ChunkedAEAD.encryptChunk(cek: kCEK, plaintext: kVec0Plaintext, chunkIndex: 0, isFinal: true)
        // Drop the last byte so the frame is one byte short.
        framed = framed.dropLast(1)
        #expect(throws: (any Error).self) {
            try ChunkedAEAD.decryptChunk(cek: kCEK, framedChunk: framed, chunkIndex: 0)
        }
    }

    @Test("Wrong CEK length (31 bytes) throws badCekLength")
    func badCekLength() {
        let shortKey = Data(repeating: 0x42, count: 31)
        #expect(throws: (any Error).self) {
            try ChunkedAEAD.encryptChunk(cek: shortKey, plaintext: Data("hi".utf8), chunkIndex: 0, isFinal: true)
        }
        let framed = try! ChunkedAEAD.encryptChunk(cek: kCEK, plaintext: Data("hi".utf8), chunkIndex: 0, isFinal: true)
        #expect(throws: (any Error).self) {
            try ChunkedAEAD.decryptChunk(cek: shortKey, framedChunk: framed, chunkIndex: 0)
        }
    }

    @Test("Bit-flip in ciphertext body causes AEAD tag failure")
    func bitFlipInCiphertext() throws {
        var framed = try ChunkedAEAD.encryptChunk(cek: kCEK, plaintext: kVec0Plaintext, chunkIndex: 0, isFinal: true)
        // Flip a bit in the ciphertext body (byte 29 is first ct byte after 4-header + 24-nonce).
        let ctStart = framed.startIndex + 29
        framed[ctStart] ^= 0x01
        #expect(throws: (any Error).self) {
            try ChunkedAEAD.decryptChunk(cek: kCEK, framedChunk: framed, chunkIndex: 0)
        }
    }

    // -----------------------------------------------------------------------
    // Header wire-format unit tests
    // -----------------------------------------------------------------------

    @Test("Frame header encodes isFinal bit correctly")
    func headerFinalBit() throws {
        let nonFinal = try ChunkedAEAD.encryptChunkWithNonce(
            cek: kCEK, plaintext: Data(count: 5),
            chunkIndex: 0, isFinal: false,
            nonce24: Data(count: 24)
        )
        let final_ = try ChunkedAEAD.encryptChunkWithNonce(
            cek: kCEK, plaintext: Data(count: 5),
            chunkIndex: 0, isFinal: true,
            nonce24: Data(count: 24)
        )
        // isFinal=false: bit 31 of header must be 0
        #expect((nonFinal[nonFinal.startIndex] & 0x80) == 0x00)
        // isFinal=true: bit 31 of header must be 1
        #expect((final_[final_.startIndex] & 0x80) == 0x80)
    }

    @Test("Frame header encodes plaintext length in bits 0..30")
    func headerLengthField() throws {
        let length = 0x00_AB_CD_EF
        let framed = try ChunkedAEAD.encryptChunkWithNonce(
            cek: kCEK, plaintext: Data(repeating: 0, count: length),
            chunkIndex: 0, isFinal: false,
            nonce24: Data(count: 24)
        )
        let b = framed
        let decoded = (Int(b[b.startIndex] & 0x7f) << 24)
                    | (Int(b[b.startIndex + 1]) << 16)
                    | (Int(b[b.startIndex + 2]) <<  8)
                    |  Int(b[b.startIndex + 3])
        #expect(decoded == length)
    }

    @Test("AAD is correct: u32_be(chunkIndex) || u8(isFinal)")
    func aadEncoding() {
        let aad = ChunkedAEAD.makeAAD(chunkIndex: 0x01_02_03_04, isFinal: true)
        #expect(aad == Data([0x01, 0x02, 0x03, 0x04, 0x01]))

        let aad2 = ChunkedAEAD.makeAAD(chunkIndex: 0, isFinal: false)
        #expect(aad2 == Data([0x00, 0x00, 0x00, 0x00, 0x00]))
    }
}

// MARK: - Argon2id interop tests

@Suite("Argon2id — web↔iOS interop")
struct Argon2InteropTests {

    /// Fixed vector generated by @noble/hashes argon2id:
    ///   password="passphrase", salt=0x01*16, m=65536, t=3, p=4, hashLen=32
    @Test("Known-answer test matches @noble/hashes output")
    func knownAnswerTest() async throws {
        let password = "passphrase".data(using: .utf8)!
        let salt = Data(repeating: 0x01, count: 16)
        let saltB64 = salt.base64EncodedString()

        let params = Argon2.Params(
            algorithm: "argon2id",
            version: 19,
            m: 65536,
            t: 3,
            p: 4,
            hash_len: 32,
            salt_b64: saltB64
        )

        let (wrapKey, _) = try await Argon2.deriveWrapKey(
            entropy: password,
            params: .existing(params)
        )
        let hashData = wrapKey.withUnsafeBytes { Data($0) }

        let expected = Data(base64Encoded: kArgon2ExpectedB64)!
        #expect(hashData == expected)
    }

    @Test("Params validation — m too low is rejected")
    func paramsValidationMemoryLow() async {
        let salt = Data(repeating: 0x01, count: 16)
        let params = Argon2.Params(
            algorithm: "argon2id", version: 19,
            m: 100,     // below minMemoryKiB (8192)
            t: 3, p: 4, hash_len: 32,
            salt_b64: salt.base64EncodedString()
        )
        await #expect(throws: (any Error).self) {
            try await Argon2.deriveWrapKey(entropy: Data("x".utf8), params: .existing(params))
        }
    }

    @Test("Params validation — unsupported algorithm is rejected")
    func paramsValidationAlgorithm() async {
        let salt = Data(repeating: 0x01, count: 16)
        let params = Argon2.Params(
            algorithm: "argon2d",   // not argon2id
            version: 19,
            m: 65536, t: 3, p: 4, hash_len: 32,
            salt_b64: salt.base64EncodedString()
        )
        await #expect(throws: (any Error).self) {
            try await Argon2.deriveWrapKey(entropy: Data("x".utf8), params: .existing(params))
        }
    }
}

// MARK: - HKDF-SHA256 interop tests

@Suite("HKDF-SHA256 — web↔iOS interop")
struct HKDFInteropTests {

    /// Fixed vector generated by @noble/hashes hkdf:
    ///   ikm=0x03*32, salt=0x04*16, info="cfemail-test", L=32
    @Test("Known-answer test matches @noble/hashes output")
    func knownAnswerTest() throws {
        let ikm = SymmetricKey(data: Data(repeating: 0x03, count: 32))
        let salt = Data(repeating: 0x04, count: 16)
        let info = Data("cfemail-test".utf8)

        let derived = HKDF<SHA256>.deriveKey(
            inputKeyMaterial: ikm,
            salt: salt,
            info: info,
            outputByteCount: 32
        )
        let derivedData = derived.withUnsafeBytes { Data($0) }

        let expected = Data(base64Encoded: kHkdfExpectedB64)!
        #expect(derivedData == expected)
    }

    /// The `deriveWrapKey` helper uses HKDF with a fixed info string.
    @Test("deriveWrapKey produces stable output for the same PRF input")
    func deriveWrapKeyDeterministic() {
        let prf = Data(repeating: 0xAA, count: 32)
        let key1 = Crypto.deriveWrapKey(prfOutput: prf)
        let key2 = Crypto.deriveWrapKey(prfOutput: prf)
        #expect(
            key1.withUnsafeBytes { Data($0) } ==
            key2.withUnsafeBytes { Data($0) }
        )
    }
}

// MARK: - Sealed-box round-trip tests

@Suite("Sealed-box — round-trip")
struct SealedBoxTests {

    @Test("sealToSelf / openSealedBox round-trip")
    func roundTrip() throws {
        let (priv, pub) = Crypto.newX25519Keypair()
        let message = Data("secret message".utf8)
        let sealed = try Crypto.sealToSelf(message, pub: pub)
        let recovered = try Crypto.openSealedBox(sealed, priv: priv)
        #expect(recovered == message)
    }

    @Test("openSealedBox fails with wrong private key")
    func wrongPrivKey() throws {
        let (_, pub) = Crypto.newX25519Keypair()
        let (wrongPriv, _) = Crypto.newX25519Keypair()
        let sealed = try Crypto.sealToSelf(Data("payload".utf8), pub: pub)
        #expect(throws: (any Error).self) {
            try Crypto.openSealedBox(sealed, priv: wrongPriv)
        }
    }

    @Test("openSealedBox fails on truncated blob")
    func truncatedBlob() {
        let truncated = Data(repeating: 0x00, count: 71)   // < 32+24+16
        #expect(throws: (any Error).self) {
            try Crypto.openSealedBox(truncated, priv: Data(repeating: 0x01, count: 32))
        }
    }

    @Test("sealToSelf / openSealedString round-trip with UTF-8 string")
    func stringRoundTrip() throws {
        let (priv, pub) = Crypto.newX25519Keypair()
        let text = "Hello, 世界! 🔐"
        let sealed = try Crypto.sealToSelf(Data(text.utf8), pub: pub)
        let recovered = try Crypto.openSealedString(sealed, priv: priv)
        #expect(recovered == text)
    }

    @Test("publicKey(forPrivate:) recovers correct public key")
    func pubkeyRecovery() throws {
        let (priv, pub) = Crypto.newX25519Keypair()
        let derived = try Crypto.publicKey(forPrivate: priv)
        #expect(derived == pub)
    }
}

// MARK: - Uploader chunking tests
//
// These tests exercise only the pure chunking + transform logic via
// `Uploader.iterateChunks`. No network calls are made.

@Suite("Uploader — chunking logic")
struct UploaderChunkingTests {

    // Write `byteCount` bytes (all equal to `fill`) to a temp file and return its URL.
    private func makeTempFile(byteCount: Int, fill: UInt8 = 0xAB) throws -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("uploader-test-\(UUID().uuidString).bin")
        let data = Data(repeating: fill, count: byteCount)
        try data.write(to: url)
        return url
    }

    // MARK: Chunk count

    @Test("12 MiB file splits into 3 chunks at 5 MiB/chunk")
    func chunkCountFor12MiB() throws {
        let size = 12 * 1024 * 1024  // exactly 2 full + 1 partial (2 MiB remainder)
        let url  = try makeTempFile(byteCount: size)
        defer { try? FileManager.default.removeItem(at: url) }

        var partNumbers: [Int] = []
        try Uploader.iterateChunks(source: url, transform: nil) { partNumber, _ in
            partNumbers.append(partNumber)
        }

        // ceil(12 MiB / 5 MiB) = 3
        #expect(partNumbers == [1, 2, 3])
    }

    @Test("Zero-byte file produces exactly one chunk")
    func emptyFileProducesOneChunk() throws {
        let url = try makeTempFile(byteCount: 0)
        defer { try? FileManager.default.removeItem(at: url) }

        var count = 0
        try Uploader.iterateChunks(source: url, transform: nil) { _, wire in
            count += 1
            #expect(wire.isEmpty)
        }
        #expect(count == 1)
    }

    @Test("Exactly 5 MiB file produces one chunk (no partial tail)")
    func exactlyOneChunk() throws {
        let size = 5 * 1024 * 1024
        let url  = try makeTempFile(byteCount: size)
        defer { try? FileManager.default.removeItem(at: url) }

        var partNumbers: [Int] = []
        try Uploader.iterateChunks(source: url, transform: nil) { partNumber, _ in
            partNumbers.append(partNumber)
        }
        #expect(partNumbers == [1])
    }

    // MARK: Total byte count with XOR transform

    @Test("XOR transform preserves total byte count across 12 MiB")
    func xorTransformByteCount() throws {
        let size: Int    = 12 * 1024 * 1024
        let xorByte: UInt8 = 0x5A
        let url = try makeTempFile(byteCount: size, fill: 0xAB)
        defer { try? FileManager.default.removeItem(at: url) }

        let xorTransform: ChunkTransform = { plaintext, _, _ in
            Data(plaintext.map { $0 ^ xorByte })
        }

        var totalWireBytes = 0
        try Uploader.iterateChunks(source: url, transform: xorTransform) { _, wire in
            totalWireBytes += wire.count
        }

        // XOR is length-preserving, so wire bytes == plaintext bytes.
        #expect(totalWireBytes == size)
    }

    @Test("XOR transform applied to each chunk is invertible")
    func xorTransformInvertible() throws {
        let size: Int    = 7 * 1024 * 1024
        let fill: UInt8  = 0xCD
        let xorByte: UInt8 = 0x37
        let url = try makeTempFile(byteCount: size, fill: fill)
        defer { try? FileManager.default.removeItem(at: url) }

        let xorTransform: ChunkTransform = { plaintext, _, _ in
            Data(plaintext.map { $0 ^ xorByte })
        }

        var reconstructed = Data()
        try Uploader.iterateChunks(source: url, transform: xorTransform) { _, wire in
            // XOR again to recover the original bytes.
            reconstructed.append(contentsOf: wire.map { $0 ^ xorByte })
        }

        #expect(reconstructed == Data(repeating: fill, count: size))
    }

    // MARK: Round-trip with real ChunkedAEAD

    @Test("ChunkedAEAD transform: encrypt then decrypt recovers plaintext")
    func chunkedAEADRoundTrip() throws {
        let chunkSize  = 5 * 1024 * 1024
        let totalSize  = 7 * 1024 * 1024  // 1 full chunk + 2 MiB tail
        let fill: UInt8 = 0x7E
        let cek         = Data(repeating: 0x42, count: 32)
        let url = try makeTempFile(byteCount: totalSize, fill: fill)
        defer { try? FileManager.default.removeItem(at: url) }

        let encryptTransform: ChunkTransform = { plaintext, idx, isFinal in
            try ChunkedAEAD.encryptChunk(
                cek: cek,
                plaintext: plaintext,
                chunkIndex: UInt32(idx),
                isFinal: isFinal
            )
        }

        // Collect (chunkIndex, ciphertext) pairs.
        var encryptedChunks: [(index: Int, data: Data)] = []
        try Uploader.iterateChunks(source: url, chunkSize: chunkSize, transform: encryptTransform) { partNumber, wire in
            encryptedChunks.append((partNumber - 1, wire))   // back to 0-based index
        }

        #expect(encryptedChunks.count == 2)  // ceil(7 MiB / 5 MiB) = 2

        // Decrypt each chunk and verify plaintext.
        var recoveredPlaintext = Data()
        for (idx, ciphertext) in encryptedChunks {
            let (plaintext, _) = try ChunkedAEAD.decryptChunk(
                cek: cek,
                framedChunk: ciphertext,
                chunkIndex: UInt32(idx)
            )
            recoveredPlaintext.append(plaintext)
        }

        #expect(recoveredPlaintext == Data(repeating: fill, count: totalSize))
    }

    @Test("isFinal flag set only on last chunk")
    func isFinalOnlyLastChunk() throws {
        let chunkSize = 5 * 1024 * 1024
        let totalSize = 11 * 1024 * 1024  // 2 full + 1 MiB tail → 3 chunks
        let cek       = Data(repeating: 0x11, count: 32)
        let url = try makeTempFile(byteCount: totalSize)
        defer { try? FileManager.default.removeItem(at: url) }

        var isFinalFlags: [Bool] = []
        let encryptTransform: ChunkTransform = { plaintext, idx, isFinal in
            isFinalFlags.append(isFinal)
            return try ChunkedAEAD.encryptChunk(
                cek: cek, plaintext: plaintext,
                chunkIndex: UInt32(idx), isFinal: isFinal
            )
        }

        try Uploader.iterateChunks(source: url, chunkSize: chunkSize, transform: encryptTransform) { _, _ in }

        #expect(isFinalFlags == [false, false, true])
    }
}

// MARK: - SecretLinkKDF interop tests

@Suite("SecretLinkKDF — web↔iOS interop")
struct SecretLinkKDFTests {

    // Load the secretLinkKDF vector from InteropVectors.json (generated by
    // scripts/gen-ios-interop-vectors.mjs). The vector was produced by running
    // @noble/hashes argon2id and hkdf with the same info strings used in
    // web/src/lib/secret-link.ts, so a passing test proves exact wire-level
    // compatibility between the web and iOS implementations.
    private func loadVector() throws -> SecretLinkKDFVector {
        let bundle = Bundle(for: BmailTestsHelper.self)
        guard let url = bundle.url(forResource: "InteropVectors", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let full = try? JSONDecoder().decode(FullVectors.self, from: data)
        else {
            throw TestError.vectorsNotFound
        }
        return full.secretLinkKDF
    }

    enum TestError: Error { case vectorsNotFound }

    /// Verify that `SecretLinkCrypto.derive` matches the web's check and wrapKey
    /// for the fixed test vector. This covers the full Argon2id → HKDF pipeline.
    @Test("derive matches web vector: check and wrapKey")
    func deriveMatchesWebVector() async throws {
        let v = try loadVector()
        let salt = Data(base64Encoded: v.argon_salt_b64)!
        let params = ArgonParams(
            algorithm: v.kdf_params.algorithm,
            version: v.kdf_params.version,
            m: v.kdf_params.m,
            t: v.kdf_params.t,
            p: v.kdf_params.p,
            hash_len: v.kdf_params.hash_len
        )

        let kdf = try await Task.detached(priority: .userInitiated) {
            try SecretLinkCrypto.derive(password: v.password_utf8, salt: salt, kdfParams: params)
        }.value

        let expectedCheck   = Data(base64Encoded: v.expected_check_b64)!
        let expectedWrapKey = Data(base64Encoded: v.expected_wrap_key_b64)!

        #expect(kdf.check == expectedCheck)
        #expect(kdf.wrapKey.withUnsafeBytes { Data($0) } == expectedWrapKey)
    }

    /// Verify that unwrapCEK correctly decrypts the pre-computed AES-GCM blob
    /// from the vector (iv=0x06*12, key=wrapKey, plaintext=CEK=0x42*32).
    @Test("unwrapCEK decrypts web-generated wrapped CEK")
    func unwrapCEKMatchesWebVector() async throws {
        let v = try loadVector()
        let salt = Data(base64Encoded: v.argon_salt_b64)!
        let params = ArgonParams(
            algorithm: v.kdf_params.algorithm,
            version: v.kdf_params.version,
            m: v.kdf_params.m,
            t: v.kdf_params.t,
            p: v.kdf_params.p,
            hash_len: v.kdf_params.hash_len
        )

        let kdf = try await Task.detached(priority: .userInitiated) {
            try SecretLinkCrypto.derive(password: v.password_utf8, salt: salt, kdfParams: params)
        }.value

        let wrapped = Data(base64Encoded: v.password_wrap_b64)!
        let cek = try SecretLinkCrypto.unwrapCEK(wrapped, wrapKey: kdf.wrapKey)

        // CEK in the vector is 0x42*32
        #expect(cek == Data(repeating: 0x42, count: 32))
    }

    /// Round-trip: wrapCEK then unwrapCEK recovers the original CEK.
    @Test("wrapCEK / unwrapCEK round-trip")
    func wrapUnwrapRoundTrip() async throws {
        let v = try loadVector()
        let salt = Data(base64Encoded: v.argon_salt_b64)!
        let params = ArgonParams(
            algorithm: v.kdf_params.algorithm,
            version: v.kdf_params.version,
            m: v.kdf_params.m,
            t: v.kdf_params.t,
            p: v.kdf_params.p,
            hash_len: v.kdf_params.hash_len
        )

        let kdf = try await Task.detached(priority: .userInitiated) {
            try SecretLinkCrypto.derive(password: v.password_utf8, salt: salt, kdfParams: params)
        }.value

        let originalCEK = SecretLinkCrypto.randomCEK()
        let wrapped = try SecretLinkCrypto.wrapCEK(originalCEK, wrapKey: kdf.wrapKey)
        let recovered = try SecretLinkCrypto.unwrapCEK(wrapped, wrapKey: kdf.wrapKey)
        #expect(recovered == originalCEK)
    }

    /// Verify that encryptWithCEK / decryptWithCEK round-trips (single-blob format
    /// used for subject and body — mirrors web's encryptWithCek / decryptWithCek).
    @Test("encryptWithCEK / decryptWithCEK round-trip")
    func cekEncryptDecryptRoundTrip() throws {
        let cek = try SecretLinkCrypto.randomCEK()
        let message = Data("Hello, secret world! 🔐".utf8)
        let ct = try SecretLinkCrypto.encryptWithCEK(message, cek: cek)
        let pt = try SecretLinkCrypto.decryptWithCEK(ct, cek: cek)
        #expect(pt == message)
    }

    /// Verify that wrong key fails to decrypt.
    @Test("decryptWithCEK fails with wrong key")
    func cekDecryptFailsWithWrongKey() throws {
        let cek = try SecretLinkCrypto.randomCEK()
        let wrongCek = try SecretLinkCrypto.randomCEK()
        let ct = try SecretLinkCrypto.encryptWithCEK(Data("payload".utf8), cek: cek)
        #expect(throws: (any Error).self) {
            try SecretLinkCrypto.decryptWithCEK(ct, cek: wrongCek)
        }
    }

    /// Validate ArgonParams.validate() rejects unsafe bounds.
    @Test("ArgonParams.validate rejects out-of-range memory")
    func argonParamsValidationMemory() {
        let bad = ArgonParams(algorithm: "argon2id", version: 19, m: 100, t: 3, p: 4, hash_len: 32)
        #expect(throws: (any Error).self) { try bad.validate() }
    }
}

// MARK: - DraftStateStore tests

@Suite("DraftStateStore")
struct DraftStateStoreTests {

    // Each test creates an isolated DraftStateStore instance backed by a unique
    // temp directory. This avoids any shared-global races under parallel testing.
    private func makeStore() -> DraftStateStore {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("DraftStateStoreTests-\(UUID().uuidString)", isDirectory: true)
        return DraftStateStore(rootURL: dir)
    }

    // MARK: Round-trip

    @Test("save → load round-trips CEK and file list")
    func roundTrip() {
        let store = makeStore()
        defer { try? FileManager.default.removeItem(at: store.rootURL) }

        let state = HostedDraftState(
            cekB64: Data(repeating: 0x42, count: 32).b64u,
            files: [
                HostedDraftFile(
                    r2Key: "hosted/abc123",
                    filename: "report.pdf",
                    mime: "application/pdf",
                    size: 12_000_000,
                    plaintextSize: 11_800_000,
                    chunkSize: 5 * 1024 * 1024,
                    chunkCount: 3
                )
            ]
        )
        store.saveHosted(draftID: "draft-1", state: state)
        let loaded = store.loadHosted(draftID: "draft-1")
        #expect(loaded == state)
    }

    @Test("save → load → clear leaves nothing")
    func clearRemovesState() {
        let store = makeStore()
        defer { try? FileManager.default.removeItem(at: store.rootURL) }

        let state = HostedDraftState(cekB64: Data(repeating: 0x01, count: 32).b64u, files: [])
        store.saveHosted(draftID: "draft-2", state: state)
        store.clearHosted(draftID: "draft-2")
        let loaded = store.loadHosted(draftID: "draft-2")
        #expect(loaded == nil)
    }

    // MARK: Missing file

    @Test("load of non-existent draft returns nil")
    func loadMissingReturnsNil() {
        let store = makeStore()
        defer { try? FileManager.default.removeItem(at: store.rootURL) }

        let loaded = store.loadHosted(draftID: "no-such-draft")
        #expect(loaded == nil)
    }

    // MARK: Corrupt JSON

    @Test("corrupt JSON returns nil and deletes the file")
    func corruptJSONReturnsNilAndDeletes() throws {
        let store = makeStore()
        defer { try? FileManager.default.removeItem(at: store.rootURL) }

        // Ensure the root dir exists so we can write directly.
        try FileManager.default.createDirectory(
            at: store.rootURL,
            withIntermediateDirectories: true
        )
        let url = store.stateURL(for: "corrupt")
        try Data("not valid json {{{".utf8).write(to: url)

        let loaded = store.loadHosted(draftID: "corrupt")
        #expect(loaded == nil)
        // File must be deleted so repeated loads don't keep failing.
        #expect(!FileManager.default.fileExists(atPath: url.path))
    }

    // MARK: GC

    @Test("gcStale removes files with mtime > 30 days ago")
    func gcRemovesStaleFiles() throws {
        let store = makeStore()
        defer { try? FileManager.default.removeItem(at: store.rootURL) }

        let state = HostedDraftState(cekB64: Data(repeating: 0x99, count: 32).b64u, files: [])
        store.saveHosted(draftID: "stale-draft", state: state)

        let url = store.stateURL(for: "stale-draft")
        let staleDate = Date().addingTimeInterval(-(31 * 24 * 60 * 60))
        try (url as NSURL).setResourceValue(staleDate, forKey: .contentModificationDateKey)

        store.gcStale()
        #expect(!FileManager.default.fileExists(atPath: url.path))
    }

    @Test("gcStale leaves files modified within 30 days")
    func gcRetainsRecentFiles() {
        let store = makeStore()
        defer { try? FileManager.default.removeItem(at: store.rootURL) }

        let state = HostedDraftState(cekB64: Data(repeating: 0x10, count: 32).b64u, files: [])
        store.saveHosted(draftID: "recent-draft", state: state)
        // mtime is "just now" — GC should not touch it.
        store.gcStale()
        let loaded = store.loadHosted(draftID: "recent-draft")
        #expect(loaded != nil)
    }
}

// MARK: - Supporting types

/// Helper class used only to locate the test bundle via `Bundle(for:)`.
final class BmailTestsHelper {}

/// Minimal Decodable mirror of InteropVectors.json for the large-chunk test.
private struct InteropVectors: Decodable {
    struct ChunkVector: Decodable {
        let description: String
        let plaintext_b64: String
        let chunkIndex: Int
        let isFinal: Bool
        let framedChunk_b64: String
    }
    let cek_b64: String
    let chunkedAEAD: [ChunkVector]
}

/// Full mirror of InteropVectors.json including the secretLinkKDF vector.
private struct FullVectors: Decodable {
    struct ChunkVector: Decodable {
        let description: String
        let plaintext_b64: String
        let chunkIndex: Int
        let isFinal: Bool
        let framedChunk_b64: String
    }
    let cek_b64: String
    let chunkedAEAD: [ChunkVector]
    let secretLinkKDF: SecretLinkKDFVector
}

private struct SecretLinkKDFVector: Decodable {
    struct KdfParamsJSON: Decodable {
        let algorithm: String
        let version: Int
        let m: Int
        let t: Int
        let p: Int
        let hash_len: Int
    }
    let description: String
    let password_utf8: String
    let argon_salt_b64: String
    let kdf_params: KdfParamsJSON
    let expected_check_b64: String
    let expected_wrap_key_b64: String
    let password_wrap_b64: String
}
